### ISSUE TITLE
ImportError: cannot import name 'StrEnum' from 'enum' Python3.10 windows

### ISSUE THREAD

**Issue by sachinr0** [ch3p4ll3/QBittorrentBot#50]
**Describe the bug**
Trying to run the cloned program with proper valid config.json. 
Platform: Windows 11, wsl2 - Ubuntu
Python 3.10

`Bot started
Traceback (most recent call last):
  File "/mnt/d/Projs/QBittorrentBot/main.py", line 30, in <module>
    app.run()
  File "/mnt/d/Projs/QBittorrentBot/.venv/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/mnt/d/Projs/QBittorrentBot/.venv/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/mnt/d/Projs/QBittorrentBot/.venv/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 74, in start
    await self.initialize()
  File "/mnt/d/Projs/QBittorrentBot/.venv/lib/python3.10/site-packages/pyrogram/methods/auth/initialize.py", line 46, in initialize
    self.load_plugins()
  File "/mnt/d/Projs/QBittorrentBot/.venv/lib/python3.10/site-packages/pyrogram/client.py", line 689, in load_plugins
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/d/Projs/QBittorrentBot/src/bot/plugins/callbacks/add_torrents_callbacks.py", line 6, in <module>
    from ....translator import Translator, Strings
  File "/mnt/d/Projs/QBittorrentBot/src/translator/__init__.py", line 2, in <module>
    from .strings import Strings
  File "/mnt/d/Projs/QBittorrentBot/src/translator/strings.py", line 1, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.10/enum.py)`

Tried python3.12, TgCrypto package is still not available, python 3.6 few packages wont install.

Any help to fix this is appreciated.

**Comment by ch3p4ll3** [comment]
@sachinr0 Hi, strEnum is available from python ≥ 3.11. try using it

**Comment by ch3p4ll3** [comment]
@sachinr0 Btw, I suggest u to use docker

**Comment by sachinr0** [comment]
Am planning to use this on a thin client which does not support docker, will try with python 3.11 and let you know :)

**Comment by sachinr0** [comment]
Worked with python3.11 👍

**Comment by ch3p4ll3** [comment]
@sachinr0 Noice
